;; ASCII ;;
; W: wall, D: door, k: key, g: gem, G: goal-gem, s: start, .: empty
; WgWWkWWgW
; W.WW.WWDW
; W..D.D..W
; WWWW.WWWW
; .......D.
; .WWW.WWW.
; .WWW.WWWD
; .WWWDWWW.
; sWWk.kWWG
(define (problem doors-keys-gems-7)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 door5 door6 - door
            key1 key2 key3 - key
            gem1 gem2 gem3 - gem)
  (:init (= (walls) (new-bit-matrix false 9 9))
         (= (walls) (set-index walls true 1 1))
         (= (xloc gem1) (2))
         (= (yloc gem1) (1))
         (= (walls) (set-index walls true 1 3))
         (= (walls) (set-index walls true 1 4))
         (= (xloc key1) (5))
         (= (yloc key1) (1))
         (= (walls) (set-index walls true 1 6))
         (= (walls) (set-index walls true 1 7))
         (= (xloc gem2) (8))
         (= (yloc gem2) (1))
         (= (walls) (set-index walls true 1 9))
         (= (walls) (set-index walls true 2 1))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 4))
         (= (walls) (set-index walls true 2 6))
         (= (walls) (set-index walls true 2 7))
         (= (xloc door1) (8))
         (= (yloc door1) (2))
         (locked door1)
         (= (walls) (set-index walls true 2 9))
         (= (walls) (set-index walls true 3 1))
         (= (xloc door2) (4))
         (= (yloc door2) (3))
         (locked door2)
         (= (xloc door3) (6))
         (= (yloc door3) (3))
         (locked door3)
         (= (walls) (set-index walls true 3 9))
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 3))
         (= (walls) (set-index walls true 4 4))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 7))
         (= (walls) (set-index walls true 4 8))
         (= (walls) (set-index walls true 4 9))
         (= (xloc door4) (8))
         (= (yloc door4) (5))
         (locked door4)
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 4))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 6 8))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (walls) (set-index walls true 7 4))
         (= (walls) (set-index walls true 7 6))
         (= (walls) (set-index walls true 7 7))
         (= (walls) (set-index walls true 7 8))
         (= (xloc door5) (9))
         (= (yloc door5) (7))
         (locked door5)
         (= (walls) (set-index walls true 8 2))
         (= (walls) (set-index walls true 8 3))
         (= (walls) (set-index walls true 8 4))
         (= (xloc door6) (5))
         (= (yloc door6) (8))
         (locked door6)
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 9 2))
         (= (walls) (set-index walls true 9 3))
         (= (xloc key2) (4))
         (= (yloc key2) (9))
         (= (xloc key3) (6))
         (= (yloc key3) (9))
         (= (walls) (set-index walls true 9 7))
         (= (walls) (set-index walls true 9 8))
         (= (xloc gem3) (9))
         (= (yloc gem3) (9))
         (= (xpos) (1))
         (= (ypos) (9)))
  (:goal (has gem3))
)
