;; ASCII ;;
; W: wall, D: door, k: key, g: gem, G: goal-gem, s: start, .: empty
; ....k....
; .WWW.WDW.
; .W.WkW.W.
; .W.WWW.W.
; .W.WGW.W.
; .W.WDW.W.
; .W.....W.
; .WWWgWWW.
; ..sWWWg..
(define (problem doors-keys-gems-4)
  (:domain doors-keys-gems)
  (:objects door1 door2 - door key1 key2 - key gem1 gem2 gem3 - gem)
  (:init (= (walls) (new-bit-matrix false 9 9))
         (= (xloc key1) (5))
         (= (yloc key1) (1))
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 4))
         (= (walls) (set-index walls true 2 6))
         (= (xloc door1) (7))
         (= (yloc door1) (2))
         (locked door1)
         (= (walls) (set-index walls true 2 8))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 4))
         (= (xloc key2) (5))
         (= (yloc key2) (3))
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 8))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 4))
         (= (walls) (set-index walls true 4 5))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 8))
         (= (walls) (set-index walls true 5 2))
         (= (walls) (set-index walls true 5 4))
         (= (xloc gem1) (5))
         (= (yloc gem1) (5))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 8))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 4))
         (= (xloc door2) (5))
         (= (yloc door2) (6))
         (locked door2)
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 8))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 8))
         (= (walls) (set-index walls true 8 2))
         (= (walls) (set-index walls true 8 3))
         (= (walls) (set-index walls true 8 4))
         (= (xloc gem2) (5))
         (= (yloc gem2) (8))
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 9 4))
         (= (walls) (set-index walls true 9 5))
         (= (walls) (set-index walls true 9 6))
         (= (xloc gem3) (7))
         (= (yloc gem3) (9))
         (= (xpos) (3))
         (= (ypos) (9)))
  (:goal (has gem1))
)
