;; ASCII ;;
; W: wall, D: door, k: key, g: gem, G: goal-gem, s: start, .: empty
; WW.W.W.WW
; WW.WGW.WW
; WW.WDW.WW
; WW.....WW
; sWgWWW.D.
; .WWWkWWW.
; .........
; WWWW.WWWW
; WWWk.gWWW
(define (problem doors-keys-gems-6)
  (:domain doors-keys-gems)
  (:objects door1 door2 - door key1 key2 - key gem1 gem2 gem3 - gem)
  (:init (= (walls) (new-bit-matrix false 9 9))
         (= (walls) (set-index walls true 1 1))
         (= (walls) (set-index walls true 1 2))
         (= (walls) (set-index walls true 1 4))
         (= (walls) (set-index walls true 1 6))
         (= (walls) (set-index walls true 1 8))
         (= (walls) (set-index walls true 1 9))
         (= (walls) (set-index walls true 2 1))
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 4))
         (= (xloc gem1) (5))
         (= (yloc gem1) (2))
         (= (walls) (set-index walls true 2 6))
         (= (walls) (set-index walls true 2 8))
         (= (walls) (set-index walls true 2 9))
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 4))
         (= (xloc door1) (5))
         (= (yloc door1) (3))
         (locked door1)
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 8))
         (= (walls) (set-index walls true 3 9))
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 8))
         (= (walls) (set-index walls true 4 9))
         (= (walls) (set-index walls true 5 2))
         (= (xloc gem2) (3))
         (= (yloc gem2) (5))
         (= (walls) (set-index walls true 5 4))
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 6))
         (= (xloc door2) (8))
         (= (yloc door2) (5))
         (locked door2)
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 4))
         (= (xloc key1) (5))
         (= (yloc key1) (6))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 6 8))
         (= (walls) (set-index walls true 8 1))
         (= (walls) (set-index walls true 8 2))
         (= (walls) (set-index walls true 8 3))
         (= (walls) (set-index walls true 8 4))
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 8 9))
         (= (walls) (set-index walls true 9 1))
         (= (walls) (set-index walls true 9 2))
         (= (walls) (set-index walls true 9 3))
         (= (xloc key2) (4))
         (= (yloc key2) (9))
         (= (xloc gem3) (6))
         (= (yloc gem3) (9))
         (= (walls) (set-index walls true 9 7))
         (= (walls) (set-index walls true 9 8))
         (= (walls) (set-index walls true 9 9))
         (= (xpos) (1))
         (= (ypos) (5)))
  (:goal (has gem1))
)
